package oracle.summitdi.model.services;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.NameValuePairs;
import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

import oracle.jbo.server.ViewRowImpl;

import oracle.summitdi.model.queries.readonly.CustomersSearchViewImpl;
import oracle.summitdi.model.services.common.SummitAppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 18 12:52:49 EST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SummitAppModuleImpl extends ApplicationModuleImpl implements SummitAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public SummitAppModuleImpl() {
    }

    /**
     * Container's getter for Customers.
     * @return Customers
     */
    public ViewObjectImpl getCustomers() {
        return (ViewObjectImpl) findViewObject("Customers");
    }

    /**
     * Container's getter for InventoryWarehouseView.
     * @return InventoryWarehouseView
     */
    public ViewObjectImpl getInventoryWarehouseView() {
        return (ViewObjectImpl) findViewObject("InventoryWarehouseView");
    }

    /**
     * Container's getter for AllWarehouses.
     * @return AllWarehouses
     */
    public ViewObjectImpl getAllWarehouses() {
        return (ViewObjectImpl) findViewObject("AllWarehouses");
    }

    /**
     * Container's getter for WarehouseMaster.
     * @return WarehouseMaster
     */
    public ViewObjectImpl getWarehouseMaster() {
        return (ViewObjectImpl) findViewObject("WarehouseMaster");
    }

    /**
     * Container's getter for InventoryDetail.
     * @return InventoryDetail
     */
    public ViewObjectImpl getInventoryDetail() {
        return (ViewObjectImpl) findViewObject("InventoryDetail");
    }

    /**
     * Container's getter for InventoryWarehouseLink.
     * @return InventoryWarehouseLink
     */
    public ViewLinkImpl getInventoryWarehouseLink() {
        return (ViewLinkImpl) findViewLink("InventoryWarehouseLink");
    }

    /**
     * Filters the WarehouseMaster view with a given warehouseId.
     * @param warehouseId
     */
    public void FilterWarehouseMasterById(String warehouseId) {
        ViewObjectImpl vo = this.getWarehouseMaster();

        // Create ViewCriteria
        ViewCriteria vc = vo.createViewCriteria();
        ViewCriteriaRow vcr = vc.createViewCriteriaRow();
        vcr.setAttribute("Id", "=" + warehouseId);
        vc.add(vcr);
        
        vo.clearViewCriterias ();
        vo.applyViewCriteria (vc);
        vo.executeQuery ();
    }

    /**
     * Container's getter for CustomersSearchView1.
     * @return CustomersSearchView1
     */
    public CustomersSearchViewImpl getCustomersSearchView() {
        return (CustomersSearchViewImpl) findViewObject("CustomersSearchView");
    }
}

