package oracle.summit.model.controlpostorder;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;

import oracle.jbo.server.TransactionEvent;

import oracle.summit.base.SummitEntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 22 21:48:11 CST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpEOImpl extends SummitEntityImpl {

    //    supplier = dept
    //    product = emp;
    
    @Override
    public void postChanges(TransactionEvent transactionEvent) {
        /* If current entity is new or modified */
        if (getPostState() == STATUS_NEW || 
            getPostState() == STATUS_MODIFIED) {
            /* Get the associated supplier for the product */
            DeptEOImpl dept = getDeptEO();
            /* If there is an associated product */
            if (dept != null) {
                /* And if it's post-status is NEW */
                if (dept.getPostState() == STATUS_NEW) {
                    /*
        * Post the department first, before posting this
        * entity by calling super below
        */
                    dept.postChanges(transactionEvent);
                }
            }
        }
        super.postChanges(transactionEvent);
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(EmpEOImpl obj) {
                return obj.getId();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setId((DBSequence)value);
            }
        }
        ,
        LastName {
            public Object get(EmpEOImpl obj) {
                return obj.getLastName();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setLastName((String)value);
            }
        }
        ,
        FirstName {
            public Object get(EmpEOImpl obj) {
                return obj.getFirstName();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setFirstName((String)value);
            }
        }
        ,
        Userid {
            public Object get(EmpEOImpl obj) {
                return obj.getUserid();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setUserid((String)value);
            }
        }
        ,
        StartDate {
            public Object get(EmpEOImpl obj) {
                return obj.getStartDate();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        Comments {
            public Object get(EmpEOImpl obj) {
                return obj.getComments();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setComments((String)value);
            }
        }
        ,
        ManagerId {
            public Object get(EmpEOImpl obj) {
                return obj.getManagerId();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setManagerId((Number)value);
            }
        }
        ,
        TitleId {
            public Object get(EmpEOImpl obj) {
                return obj.getTitleId();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setTitleId((BigDecimal)value);
            }
        }
        ,
        DeptId {
            public Object get(EmpEOImpl obj) {
                return obj.getDeptId();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setDeptId((Number)value);
            }
        }
        ,
        Salary {
            public Object get(EmpEOImpl obj) {
                return obj.getSalary();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setSalary((Number)value);
            }
        }
        ,
        CommissionPct {
            public Object get(EmpEOImpl obj) {
                return obj.getCommissionPct();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setCommissionPct((Number)value);
            }
        }
        ,
        EmpEO {
            public Object get(EmpEOImpl obj) {
                return obj.getEmpEO();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ManagerIdEmpEO {
            public Object get(EmpEOImpl obj) {
                return obj.getManagerIdEmpEO();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setManagerIdEmpEO((EmpEOImpl)value);
            }
        }
        ,
        CustomerEO {
            public Object get(EmpEOImpl obj) {
                return obj.getCustomerEO();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DeptEO {
            public Object get(EmpEOImpl obj) {
                return obj.getDeptEO();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setDeptEO((DeptEOImpl)value);
            }
        }
        ,
        OrdEO {
            public Object get(EmpEOImpl obj) {
                return obj.getOrdEO();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TitleEO {
            public Object get(EmpEOImpl obj) {
                return obj.getTitleEO();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setTitleEO((SummitEntityImpl)value);
            }
        }
        ,
        WarehouseEO {
            public Object get(EmpEOImpl obj) {
                return obj.getWarehouseEO();
            }

            public void put(EmpEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(EmpEOImpl object);

        public abstract void put(EmpEOImpl object, Object value);

        public int index() {
            return EmpEOImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return EmpEOImpl.AttributesEnum.firstIndex() + EmpEOImpl.AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = EmpEOImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int USERID = AttributesEnum.Userid.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int TITLEID = AttributesEnum.TitleId.index();
    public static final int DEPTID = AttributesEnum.DeptId.index();
    public static final int SALARY = AttributesEnum.Salary.index();
    public static final int COMMISSIONPCT = AttributesEnum.CommissionPct.index();
    public static final int EMPEO = AttributesEnum.EmpEO.index();
    public static final int MANAGERIDEMPEO = AttributesEnum.ManagerIdEmpEO.index();
    public static final int CUSTOMEREO = AttributesEnum.CustomerEO.index();
    public static final int DEPTEO = AttributesEnum.DeptEO.index();
    public static final int ORDEO = AttributesEnum.OrdEO.index();
    public static final int TITLEEO = AttributesEnum.TitleEO.index();
    public static final int WAREHOUSEEO = AttributesEnum.WarehouseEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmpEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("oracle.summit.model.controlpostorder.EmpEO");
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public DBSequence getId() {
        return (DBSequence)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for LastName, using the alias name LastName.
     * @return the value of LastName
     */
    public String getLastName() {
        return (String)getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastName.
     * @param value value to set the LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for FirstName, using the alias name FirstName.
     * @return the value of FirstName
     */
    public String getFirstName() {
        return (String)getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FirstName.
     * @param value value to set the FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for Userid, using the alias name Userid.
     * @return the value of Userid
     */
    public String getUserid() {
        return (String)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Userid.
     * @param value value to set the Userid
     */
    public void setUserid(String value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for StartDate, using the alias name StartDate.
     * @return the value of StartDate
     */
    public Date getStartDate() {
        return (Date)getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartDate.
     * @param value value to set the StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for Comments, using the alias name Comments.
     * @return the value of Comments
     */
    public String getComments() {
        return (String)getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comments.
     * @param value value to set the Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for ManagerId, using the alias name ManagerId.
     * @return the value of ManagerId
     */
    public Number getManagerId() {
        return (Number)getAttributeInternal(MANAGERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManagerId.
     * @param value value to set the ManagerId
     */
    public void setManagerId(Number value) {
        setAttributeInternal(MANAGERID, value);
    }

    /**
     * Gets the attribute value for TitleId, using the alias name TitleId.
     * @return the value of TitleId
     */
    public BigDecimal getTitleId() {
        return (BigDecimal)getAttributeInternal(TITLEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TitleId.
     * @param value value to set the TitleId
     */
    public void setTitleId(BigDecimal value) {
        setAttributeInternal(TITLEID, value);
    }

    /**
     * Gets the attribute value for DeptId, using the alias name DeptId.
     * @return the value of DeptId
     */
    public Number getDeptId() {
        return (Number)getAttributeInternal(DEPTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeptId.
     * @param value value to set the DeptId
     */
    public void setDeptId(Number value) {
        setAttributeInternal(DEPTID, value);
    }

    /**
     * Gets the attribute value for Salary, using the alias name Salary.
     * @return the value of Salary
     */
    public Number getSalary() {
        return (Number)getAttributeInternal(SALARY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salary.
     * @param value value to set the Salary
     */
    public void setSalary(Number value) {
        setAttributeInternal(SALARY, value);
    }

    /**
     * Gets the attribute value for CommissionPct, using the alias name CommissionPct.
     * @return the value of CommissionPct
     */
    public Number getCommissionPct() {
        return (Number)getAttributeInternal(COMMISSIONPCT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommissionPct.
     * @param value value to set the CommissionPct
     */
    public void setCommissionPct(Number value) {
        setAttributeInternal(COMMISSIONPCT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getEmpEO() {
        return (RowIterator)getAttributeInternal(EMPEO);
    }

    /**
     * @return the associated entity EmpEOImpl.
     */
    public EmpEOImpl getManagerIdEmpEO() {
        return (EmpEOImpl)getAttributeInternal(MANAGERIDEMPEO);
    }

    /**
     * Sets <code>value</code> as the associated entity EmpEOImpl.
     */
    public void setManagerIdEmpEO(EmpEOImpl value) {
        setAttributeInternal(MANAGERIDEMPEO, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCustomerEO() {
        return (RowIterator)getAttributeInternal(CUSTOMEREO);
    }

    /**
     * @return the associated entity DeptEOImpl.
     */
    public DeptEOImpl getDeptEO() {
        return (DeptEOImpl)getAttributeInternal(DEPTEO);
    }

    /**
     * Sets <code>value</code> as the associated entity DeptEOImpl.
     */
    public void setDeptEO(DeptEOImpl value) {
        setAttributeInternal(DEPTEO, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getOrdEO() {
        return (RowIterator)getAttributeInternal(ORDEO);
    }

    /**
     * @return the associated entity oracle.summit.base.SummitEntityImpl.
     */
    public SummitEntityImpl getTitleEO() {
        return (SummitEntityImpl)getAttributeInternal(TITLEEO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.summit.base.SummitEntityImpl.
     */
    public void setTitleEO(SummitEntityImpl value) {
        setAttributeInternal(TITLEEO, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getWarehouseEO() {
        return (RowIterator)getAttributeInternal(WAREHOUSEEO);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[]{id});
    }


}
