package oracle.summit.model.invokingstoredprocedure.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Date;

import oracle.summit.model.invokingstoredprocedure.DateAndStringBean;
import oracle.summit.model.invokingstoredprocedure.common.InvokingStoredProcAppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 18 14:31:57 CDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvokingStoredProcAppModuleClient extends ApplicationModuleImpl implements InvokingStoredProcAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public InvokingStoredProcAppModuleClient() {
    }

    public String callFuncWithThreeArgs(oracle.jbo.domain.Number n, Date d, String v) {
        Object _ret = this.riInvokeExportedMethod(this,"callFuncWithThreeArgs",new String [] {"oracle.jbo.domain.Number","oracle.jbo.domain.Date","java.lang.String"},new Object[] {n, d, v});
        return (String) _ret;
    }

    public void callProcWithNoArgs() {
        Object _ret = this.riInvokeExportedMethod(this,"callProcWithNoArgs",null,null);
        return;
    }

    public DateAndStringBean callProcWithOutArgs(oracle.jbo.domain.Number n, String v) {
        Object _ret = this.riInvokeExportedMethod(this,"callProcWithOutArgs",new String [] {"oracle.jbo.domain.Number","java.lang.String"},new Object[] {n, v});
        return (DateAndStringBean) _ret;
    }

    public void callProcWithThreeArgs(oracle.jbo.domain.Number n, Date d, String v) {
        Object _ret = this.riInvokeExportedMethod(this,"callProcWithThreeArgs",new String [] {"oracle.jbo.domain.Number","oracle.jbo.domain.Date","java.lang.String"},new Object[] {n, d, v});
        return;
    }
}

