package oracle.summit.model.appmodule.service.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import oracle.summit.model.appmodule.service.common.AppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 04 08:21:48 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void doSomeCustomProcessing() {
        Object _ret = this.riInvokeExportedMethod(this,"doSomeCustomProcessing",null,null);
        return;
    }

    public String findOrderAndCustomer(long orderId) {
        Object _ret = this.riInvokeExportedMethod(this,"findOrderAndCustomer",new String [] {"long"},new Object[] {new Long(orderId)});
        return (String) _ret;
    }

    public void updateOrderStatus(long orderId, String newStatus) {
        Object _ret = this.riInvokeExportedMethod(this,"updateOrderStatus",new String [] {"long","java.lang.String"},new Object[] {new Long(orderId), newStatus});
        return;
    }
    public String findOrderTotal(long orderId) {
        Object _ret = this.riInvokeExportedMethod(this,"findOrderTotal",new String [] {"long"},new Object[] {new Long(orderId)});
        return (String) _ret;       
    }
    
    public long createCustomer(String name, String city, Integer countryId) {
    Object _ret = this.riInvokeExportedMethod(this,"updateOrderStatus",new String [] {"java.lang.String","java.lang.String","java.lang.Integer"},new Object[] {name, city, countryId});
        return ((Long)_ret).longValue();
    }
}
