
package oracle.summit.model.sdo.service.common;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.oracle.xmlns.adf.svc.types.FindControl;
import com.oracle.xmlns.adf.svc.types.FindCriteria;
import com.oracle.xmlns.adf.svc.types.ProcessControl;

import oracle.summit.model.sdo.views.common.DeptViewSDO;
import oracle.summit.model.sdo.views.common.EmpViewSDO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "HRAppModuleService", targetNamespace = "/oracle/summit/model/sdo/service/common/")
@XmlSeeAlso({
            com.oracle.xmlns.adf.svc.errors.ObjectFactory.class, com.oracle.xmlns.adf.svc.types.ObjectFactory.class,
            oracle.summit.model.sdo.service.common.types.ObjectFactory.class,
            oracle.summit.model.sdo.views.common.ObjectFactory.class, sdo.commonj.ObjectFactory.class,
            sdo.commonj.java.ObjectFactory.class, sdo.commonj.xml.ObjectFactory.class
    })
public interface HRAppModuleService {


    /**
     *
     * @param id
     * @return
     *     returns oracle.summit.model.sdo.views.common.DeptViewSDO
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/getDeptView1")
    @WebResult(name = "result", targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
    @RequestWrapper(localName = "getDeptView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.GetDeptView1")
    @ResponseWrapper(localName = "getDeptView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.GetDeptView1Response")
    public DeptViewSDO getDeptView1(@WebParam(name = "id",
                                              targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                                    int id) throws ServiceException;

    /**
     *
     * @param deptView1
     * @return
     *     returns oracle.summit.model.sdo.views.common.DeptViewSDO
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/createDeptView1")
    @WebResult(name = "result", targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
    @RequestWrapper(localName = "createDeptView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.CreateDeptView1")
    @ResponseWrapper(localName = "createDeptView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.CreateDeptView1Response")
    public DeptViewSDO createDeptView1(@WebParam(name = "deptView1",
                                                 targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                                       DeptViewSDO deptView1) throws ServiceException;

    /**
     *
     * @param deptView1
     * @return
     *     returns oracle.summit.model.sdo.views.common.DeptViewSDO
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/updateDeptView1")
    @WebResult(name = "result", targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
    @RequestWrapper(localName = "updateDeptView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.UpdateDeptView1")
    @ResponseWrapper(localName = "updateDeptView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.UpdateDeptView1Response")
    public DeptViewSDO updateDeptView1(@WebParam(name = "deptView1",
                                                 targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                                       DeptViewSDO deptView1) throws ServiceException;

    /**
     *
     * @param deptView1
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/deleteDeptView1")
    @RequestWrapper(localName = "deleteDeptView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.DeleteDeptView1")
    @ResponseWrapper(localName = "deleteDeptView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.DeleteDeptView1Response")
    public void deleteDeptView1(@WebParam(name = "deptView1",
                                          targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                                DeptViewSDO deptView1) throws ServiceException;

    /**
     *
     * @param deptView1
     * @return
     *     returns oracle.summit.model.sdo.views.common.DeptViewSDO
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/mergeDeptView1")
    @WebResult(name = "result", targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
    @RequestWrapper(localName = "mergeDeptView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.MergeDeptView1")
    @ResponseWrapper(localName = "mergeDeptView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.MergeDeptView1Response")
    public DeptViewSDO mergeDeptView1(@WebParam(name = "deptView1",
                                                targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                                      DeptViewSDO deptView1) throws ServiceException;

    /**
     *
     * @param findControl
     * @param findCriteria
     * @return
     *     returns java.util.List<oracle.summit.model.sdo.views.common.DeptViewSDO>
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/findDeptView1")
    @WebResult(name = "result", targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
    @RequestWrapper(localName = "findDeptView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.FindDeptView1")
    @ResponseWrapper(localName = "findDeptView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.FindDeptView1Response")
    public List<DeptViewSDO> findDeptView1(@WebParam(name = "findCriteria",
                                                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                                           FindCriteria findCriteria,
                                           @WebParam(name = "findControl",
                                                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                                           FindControl findControl) throws ServiceException;

    /**
     *
     * @param deptView1
     * @param processControl
     * @param changeOperation
     * @return
     *     returns java.util.List<oracle.summit.model.sdo.views.common.DeptViewSDO>
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/processDeptView1")
    @WebResult(name = "result", targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
    @RequestWrapper(localName = "processDeptView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.ProcessDeptView1")
    @ResponseWrapper(localName = "processDeptView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.ProcessDeptView1Response")
    public List<DeptViewSDO> processDeptView1(@WebParam(name = "changeOperation",
                                                        targetNamespace =
                                                        "/oracle/summit/model/sdo/service/common/types/")
                                              String changeOperation,
                                              @WebParam(name = "deptView1",
                                                        targetNamespace =
                                                        "/oracle/summit/model/sdo/service/common/types/")
                                              List<DeptViewSDO> deptView1,
                                              @WebParam(name = "processControl",
                                                        targetNamespace =
                                                        "/oracle/summit/model/sdo/service/common/types/")
                                              ProcessControl processControl) throws ServiceException;

    /**
     *
     * @param id
     * @return
     *     returns oracle.summit.model.sdo.views.common.EmpViewSDO
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/getEmpView1")
    @WebResult(name = "result", targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
    @RequestWrapper(localName = "getEmpView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.GetEmpView1")
    @ResponseWrapper(localName = "getEmpView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.GetEmpView1Response")
    public EmpViewSDO getEmpView1(@WebParam(name = "id",
                                            targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                                  int id) throws ServiceException;

    /**
     *
     * @param empView1
     * @return
     *     returns oracle.summit.model.sdo.views.common.EmpViewSDO
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/createEmpView1")
    @WebResult(name = "result", targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
    @RequestWrapper(localName = "createEmpView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.CreateEmpView1")
    @ResponseWrapper(localName = "createEmpView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.CreateEmpView1Response")
    public EmpViewSDO createEmpView1(@WebParam(name = "empView1",
                                               targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                                     EmpViewSDO empView1) throws ServiceException;

    /**
     *
     * @param empView1
     * @return
     *     returns oracle.summit.model.sdo.views.common.EmpViewSDO
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/updateEmpView1")
    @WebResult(name = "result", targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
    @RequestWrapper(localName = "updateEmpView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.UpdateEmpView1")
    @ResponseWrapper(localName = "updateEmpView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.UpdateEmpView1Response")
    public EmpViewSDO updateEmpView1(@WebParam(name = "empView1",
                                               targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                                     EmpViewSDO empView1) throws ServiceException;

    /**
     *
     * @param empView1
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/deleteEmpView1")
    @RequestWrapper(localName = "deleteEmpView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.DeleteEmpView1")
    @ResponseWrapper(localName = "deleteEmpView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.DeleteEmpView1Response")
    public void deleteEmpView1(@WebParam(name = "empView1",
                                         targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                               EmpViewSDO empView1) throws ServiceException;

    /**
     *
     * @param empView1
     * @return
     *     returns oracle.summit.model.sdo.views.common.EmpViewSDO
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/mergeEmpView1")
    @WebResult(name = "result", targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
    @RequestWrapper(localName = "mergeEmpView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.MergeEmpView1")
    @ResponseWrapper(localName = "mergeEmpView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.MergeEmpView1Response")
    public EmpViewSDO mergeEmpView1(@WebParam(name = "empView1",
                                              targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                                    EmpViewSDO empView1) throws ServiceException;

    /**
     *
     * @param findControl
     * @param findCriteria
     * @return
     *     returns java.util.List<oracle.summit.model.sdo.views.common.EmpViewSDO>
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/findEmpView1")
    @WebResult(name = "result", targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
    @RequestWrapper(localName = "findEmpView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.FindEmpView1")
    @ResponseWrapper(localName = "findEmpView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.FindEmpView1Response")
    public List<EmpViewSDO> findEmpView1(@WebParam(name = "findCriteria",
                                                   targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                                         FindCriteria findCriteria,
                                         @WebParam(name = "findControl",
                                                   targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
                                         FindControl findControl) throws ServiceException;

    /**
     *
     * @param findControl
     * @param bvDName
     * @param findCriteria
     * @return
     *     returns java.util.List<oracle.summit.model.sdo.views.common.EmpViewSDO>
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/findEmpView1ByDeptVC")
    @WebResult(name = "result", targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
    @RequestWrapper(localName = "findEmpView1ByDeptVC",
                    targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.FindEmpView1ByDeptVC")
    @ResponseWrapper(localName = "findEmpView1ByDeptVCResponse",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.FindEmpView1ByDeptVCResponse")
    public List<EmpViewSDO> findEmpView1ByDeptVC(@WebParam(name = "findCriteria",
                                                           targetNamespace =
                                                           "/oracle/summit/model/sdo/service/common/types/")
                                                 FindCriteria findCriteria,
                                                 @WebParam(name = "bv_dName",
                                                           targetNamespace =
                                                           "/oracle/summit/model/sdo/service/common/types/")
                                                 String bvDName,
                                                 @WebParam(name = "findControl",
                                                           targetNamespace =
                                                           "/oracle/summit/model/sdo/service/common/types/")
                                                 FindControl findControl) throws ServiceException;

    /**
     *
     * @param processControl
     * @param empView1
     * @param changeOperation
     * @return
     *     returns java.util.List<oracle.summit.model.sdo.views.common.EmpViewSDO>
     * @throws ServiceException
     */
    @WebMethod(action = "/oracle/summit/model/sdo/service/common/processEmpView1")
    @WebResult(name = "result", targetNamespace = "/oracle/summit/model/sdo/service/common/types/")
    @RequestWrapper(localName = "processEmpView1", targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    className = "oracle.summit.model.sdo.service.common.types.ProcessEmpView1")
    @ResponseWrapper(localName = "processEmpView1Response",
                     targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     className = "oracle.summit.model.sdo.service.common.types.ProcessEmpView1Response")
    public List<EmpViewSDO> processEmpView1(@WebParam(name = "changeOperation",
                                                      targetNamespace =
                                                      "/oracle/summit/model/sdo/service/common/types/")
                                            String changeOperation,
                                            @WebParam(name = "empView1",
                                                      targetNamespace =
                                                      "/oracle/summit/model/sdo/service/common/types/")
                                            List<EmpViewSDO> empView1,
                                            @WebParam(name = "processControl",
                                                      targetNamespace =
                                                      "/oracle/summit/model/sdo/service/common/types/")
                                            ProcessControl processControl) throws ServiceException;

}
