package oracle.summitdi.model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 18 13:00:41 EST 2014
// ---------------------------------------------------------------------
public interface SummitAppModule extends ApplicationModule {
    void FilterWarehouseMasterById(String warehouseId);
}

