package oracle.summit.model.multinamedviewcriteria.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 07 15:56:58 CST 2013
// ---------------------------------------------------------------------
public interface CustomerView extends ViewObject {
    Integer getbv_CreditRatingId();

    Integer getbv_SalesRepId();

    void setbv_CreditRatingId(Integer value);

    void setbv_SalesRepId(Integer value);

    void showCustomersForCreditRating();

    void showCustomersForSalesRep();

    void showCustomersForSalesRepForCreditRating();

    void showAllCustomers();
}

