package oracle.summit.model.extend.client;

import oracle.jbo.client.remote.ViewUsageImpl;

import oracle.summit.model.extend.common.ProductView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 16 15:33:48 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductViewClient extends ViewUsageImpl implements ProductView {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductViewClient() {
    }

    public void someCustomMethodOnProducts(String arg) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"someCustomMethodOnProducts",new String [] {"java.lang.String"},new Object[] {arg});
        return;
    }
}
