package oracle.summit.model.extend.client;

import oracle.summit.model.extend.common.ProductViewEx;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 16 15:48:19 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductViewExClient extends ProductViewClient implements ProductViewEx {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductViewExClient() {
    }

    public String getbv_ProductName() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getbv_ProductName",null,null);
        return (String)_ret;
    }

    public void setbv_ProductName(String value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setbv_ProductName",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }
}
