package oracle.summit.model.extend.client;

import java.math.BigDecimal;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 21 08:36:07 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductViewRowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductViewRowClient() {
    }

    public Integer getId() {
        return (Integer)getAttribute("Id");
    }

    public Integer getImageId() {
        return (Integer)getAttribute("ImageId");
    }

    public Integer getLongtextId() {
        return (Integer)getAttribute("LongtextId");
    }

    public String getName() {
        return (String)getAttribute("Name");
    }

    public String getShortDesc() {
        return (String)getAttribute("ShortDesc");
    }

    public String getSomeValue() {
        return (String)getAttribute("SomeValue");
    }

    public BigDecimal getSuggestedWhlslPrice() {
        return (BigDecimal)getAttribute("SuggestedWhlslPrice");
    }

    public String getWhlslUnits() {
        return (String)getAttribute("WhlslUnits");
    }

    public void setId(Integer value) {
        setAttribute("Id", value);
    }

    public void setImageId(Integer value) {
        setAttribute("ImageId", value);
    }

    public void setLongtextId(Integer value) {
        setAttribute("LongtextId", value);
    }

    public void setName(String value) {
        setAttribute("Name", value);
    }

    public void setShortDesc(String value) {
        setAttribute("ShortDesc", value);
    }

    public void setSomeValue(String value) {
        setAttribute("SomeValue", value);
    }

    public void setSuggestedWhlslPrice(BigDecimal value) {
        setAttribute("SuggestedWhlslPrice", value);
    }

    public void setWhlslUnits(String value) {
        setAttribute("WhlslUnits", value);
    }
}
