package oracle.summit.model.extend.client;

import java.math.BigDecimal;

import oracle.jbo.client.remote.RowImpl;

import oracle.summit.model.extend.common.ProductViewExRow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 16 15:41:57 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductViewExRowClient extends RowImpl implements ProductViewExRow {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductViewExRowClient() {
    }

    public Integer getId() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getId",null,null);
        return (Integer)_ret;
    }

    public Integer getImageId() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getImageId",null,null);
        return (Integer)_ret;
    }

    public Integer getLongtextId() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getLongtextId",null,null);
        return (Integer)_ret;
    }

    public String getName() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getName",null,null);
        return (String)_ret;
    }

    public String getShortDesc() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getShortDesc",null,null);
        return (String)_ret;
    }

    public String getSomeValue() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getSomeValue",null,null);
        return (String)_ret;
    }

    public BigDecimal getSuggestedWhlslPrice() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getSuggestedWhlslPrice",null,null);
        return (BigDecimal)_ret;
    }

    public String getWhlslUnits() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getWhlslUnits",null,null);
        return (String)_ret;
    }

    public void setId(Integer value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setId",new String [] {"java.lang.Integer"},new Object[] {value});
        return;
    }

    public void setImageId(Integer value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setImageId",new String [] {"java.lang.Integer"},new Object[] {value});
        return;
    }

    public void setLongtextId(Integer value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setLongtextId",new String [] {"java.lang.Integer"},new Object[] {value});
        return;
    }

    public void setName(String value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setName",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }

    public void setShortDesc(String value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setShortDesc",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }

    public void setSomeValue(String value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setSomeValue",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }

    public void setSuggestedWhlslPrice(BigDecimal value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setSuggestedWhlslPrice",new String [] {"java.math.BigDecimal"},new Object[] {value});
        return;
    }

    public void setWhlslUnits(String value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setWhlslUnits",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }
    
    public void someExtraFeature(String x) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"someExtraFeature",new String [] {"java.lang.String"},new Object[] {x});
        return;
    }
}
