package oracle.summit.model.controlpostorder.common;

import oracle.jbo.ApplicationModule;

import oracle.summit.model.controlpostorder.Result;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 14 07:23:53 CDT 2012
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    Result newEmployeeForNewDepartment(String deptName, oracle.jbo.domain.Number regionId, String lastName,
                                       String firstName, oracle.jbo.domain.Number salary);
}
