package oracle.summit.model.polymorphicvo.service.common.serviceinterface;

import commonj.sdo.DataObject;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.common.service.types.ProcessControl;
import oracle.jbo.service.errors.ServiceException;

import oracle.summit.model.polymorphicvo.views.common.SDeptViewSDO;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 12 13:25:03 CST 2014
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/", name = "AppModuleService",
                    wsdlLocation =
                    "oracle/summit/model/polymorphicvo/service/common/serviceinterface/AppModuleService.wsdl")
@SDODatabinding(schemaLocation =
                "oracle/summit/model/polymorphicvo/service/common/serviceinterface/AppModuleService.xsd")
public interface AppModuleService {
    public static final String NAME = "{http://xmlns.oracle.com/apps/hr/service/}AppModuleService";

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/getSDeptView1", operationName = "getSDeptView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "getSDeptView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "getSDeptView1Response")
    @WebResult(name = "result")
    SDeptViewSDO getSDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "id") Integer id) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/createSDeptView1", operationName = "createSDeptView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "createSDeptView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "createSDeptView1Response")
    @WebResult(name = "result")
    SDeptViewSDO createSDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "sDeptView1")
                                  SDeptViewSDO sDeptView1) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/updateSDeptView1", operationName = "updateSDeptView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "updateSDeptView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "updateSDeptView1Response")
    @WebResult(name = "result")
    SDeptViewSDO updateSDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "sDeptView1")
                                  SDeptViewSDO sDeptView1) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/deleteSDeptView1", operationName = "deleteSDeptView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "deleteSDeptView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "deleteSDeptView1Response")
    void deleteSDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "sDeptView1")
                          SDeptViewSDO sDeptView1) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/mergeSDeptView1", operationName = "mergeSDeptView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "mergeSDeptView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "mergeSDeptView1Response")
    @WebResult(name = "result")
    SDeptViewSDO mergeSDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "sDeptView1")
                                 SDeptViewSDO sDeptView1) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/findSDeptView1", operationName = "findSDeptView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "findSDeptView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "findSDeptView1Response")
    @WebResult(name = "result")
    List<SDeptViewSDO> findSDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                      FindCriteria findCriteria,
                                      @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                      FindControl findControl) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/processSDeptView1",
               operationName = "processSDeptView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "processSDeptView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "processSDeptView1Response")
    @WebResult(name = "result")
    List<SDeptViewSDO> processSDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "changeOperation")
                                         String changeOperation,
                                         @WebParam(mode = WebParam.Mode.IN, name = "sDeptView1")
                                         List<SDeptViewSDO> sDeptView1,
                                         @WebParam(mode = WebParam.Mode.IN, name = "processControl")
                                         ProcessControl processControl) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/getSEmpView1", operationName = "getSEmpView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "getSEmpView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "getSEmpView1Response")
    @WebResult(name = "result")
    DataObject getSEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "id") Integer id) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/createSEmpView1", operationName = "createSEmpView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "createSEmpView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "createSEmpView1Response")
    @WebResult(name = "result")
    DataObject createSEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "sEmpView1")
                               DataObject sEmpView1) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/updateSEmpView1", operationName = "updateSEmpView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "updateSEmpView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "updateSEmpView1Response")
    @WebResult(name = "result")
    DataObject updateSEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "sEmpView1")
                               DataObject sEmpView1) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/deleteSEmpView1", operationName = "deleteSEmpView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "deleteSEmpView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "deleteSEmpView1Response")
    void deleteSEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "sEmpView1")
                         DataObject sEmpView1) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/mergeSEmpView1", operationName = "mergeSEmpView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "mergeSEmpView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "mergeSEmpView1Response")
    @WebResult(name = "result")
    DataObject mergeSEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "sEmpView1")
                              DataObject sEmpView1) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/findSEmpView1", operationName = "findSEmpView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "findSEmpView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "findSEmpView1Response")
    @WebResult(name = "result")
    List<DataObject> findSEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria") FindCriteria findCriteria,
                                   @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                   FindControl findControl) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/findSEmpView1ByDept",
               operationName = "findSEmpView1ByDept")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                    localName = "findSEmpView1ByDept")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "findSEmpView1ByDeptResponse")
    @WebResult(name = "result")
    List<DataObject> findSEmpView1ByDept(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                         FindCriteria findCriteria,
                                         @WebParam(mode = WebParam.Mode.IN, name = "bv_dName") String bv_dName,
                                         @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                         FindControl findControl) throws ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/hr/service/processSEmpView1", operationName = "processSEmpView1")
    @RequestWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/", localName = "processSEmpView1")
    @ResponseWrapper(targetNamespace = "http://xmlns.oracle.com/apps/hr/service/types/",
                     localName = "processSEmpView1Response")
    @WebResult(name = "result")
    List<DataObject> processSEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "changeOperation")
                                      String changeOperation,
                                      @WebParam(mode = WebParam.Mode.IN, name = "sEmpView1") List<DataObject> sEmpView1,
                                      @WebParam(mode = WebParam.Mode.IN, name = "processControl")
                                      ProcessControl processControl) throws ServiceException;
}

