package oracle.summit.model.multieoupdate;

import oracle.summit.base.SummitViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 27 14:25:33 CDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductInventoryVOImpl extends SummitViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductInventoryVOImpl() {
    }
}

