package oracle.summitdi.model.queries.readonly.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 20 14:48:42 EST 2014
// ---------------------------------------------------------------------
public interface CustomersSearchView extends ViewObject {
    void executeCountriesQuery(String searchTerm);

    void resetQueryValues();
}

