package oracle.summit.model.sdo.service.common.serviceinterface;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.common.service.types.ProcessControl;
import oracle.jbo.service.errors.ServiceException;

import oracle.summit.model.sdo.views.common.DeptViewSDO;
import oracle.summit.model.sdo.views.common.EmpViewSDO;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 13 14:01:05 CST 2015
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace = "/oracle/summit/model/sdo/service/common/", name = "HRAppModuleService",
                    wsdlLocation = "oracle/summit/model/sdo/service/common/serviceinterface/HRAppModuleService.wsdl")
@SDODatabinding(schemaLocation = "oracle/summit/model/sdo/service/common/serviceinterface/HRAppModuleService.xsd")
public interface HRAppModuleService {
    public static final String NAME = "{/oracle/summit/model/sdo/service/common/}HRAppModuleService";

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/getDeptView1", operationName = "getDeptView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "getDeptView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "getDeptView1Response")
    @WebResult(name = "result")
    DeptViewSDO getDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "id") Integer id) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/createDeptView1", operationName = "createDeptView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "createDeptView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "createDeptView1Response")
    @WebResult(name = "result")
    DeptViewSDO createDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "deptView1")
                                DeptViewSDO deptView1) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/updateDeptView1", operationName = "updateDeptView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "updateDeptView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "updateDeptView1Response")
    @WebResult(name = "result")
    DeptViewSDO updateDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "deptView1")
                                DeptViewSDO deptView1) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/deleteDeptView1", operationName = "deleteDeptView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "deleteDeptView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "deleteDeptView1Response")
    void deleteDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "deptView1")
                         DeptViewSDO deptView1) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/mergeDeptView1", operationName = "mergeDeptView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "mergeDeptView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "mergeDeptView1Response")
    @WebResult(name = "result")
    DeptViewSDO mergeDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "deptView1")
                               DeptViewSDO deptView1) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/findDeptView1", operationName = "findDeptView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "findDeptView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "findDeptView1Response")
    @WebResult(name = "result")
    List<DeptViewSDO> findDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria") FindCriteria findCriteria,
                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/processDeptView1", operationName = "processDeptView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "processDeptView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "processDeptView1Response")
    @WebResult(name = "result")
    List<DeptViewSDO> processDeptView1(@WebParam(mode = WebParam.Mode.IN, name = "changeOperation")
                                       String changeOperation,
                                       @WebParam(mode = WebParam.Mode.IN, name = "deptView1")
                                       List<DeptViewSDO> deptView1,
                                       @WebParam(mode = WebParam.Mode.IN, name = "processControl")
                                       ProcessControl processControl) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/getEmpView1", operationName = "getEmpView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "getEmpView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "getEmpView1Response")
    @WebResult(name = "result")
    EmpViewSDO getEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "id") Integer id) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/createEmpView1", operationName = "createEmpView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "createEmpView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "createEmpView1Response")
    @WebResult(name = "result")
    EmpViewSDO createEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "empView1")
                              EmpViewSDO empView1) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/updateEmpView1", operationName = "updateEmpView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "updateEmpView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "updateEmpView1Response")
    @WebResult(name = "result")
    EmpViewSDO updateEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "empView1")
                              EmpViewSDO empView1) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/deleteEmpView1", operationName = "deleteEmpView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "deleteEmpView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "deleteEmpView1Response")
    void deleteEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "empView1")
                        EmpViewSDO empView1) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/mergeEmpView1", operationName = "mergeEmpView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "mergeEmpView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "mergeEmpView1Response")
    @WebResult(name = "result")
    EmpViewSDO mergeEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "empView1")
                             EmpViewSDO empView1) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/findEmpView1", operationName = "findEmpView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "findEmpView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "findEmpView1Response")
    @WebResult(name = "result")
    List<EmpViewSDO> findEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria") FindCriteria findCriteria,
                                  @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                  FindControl findControl) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/findEmpView1ByDeptVC",
               operationName = "findEmpView1ByDeptVC")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                    localName = "findEmpView1ByDeptVC")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "findEmpView1ByDeptVCResponse")
    @WebResult(name = "result")
    List<EmpViewSDO> findEmpView1ByDeptVC(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                          FindCriteria findCriteria,
                                          @WebParam(mode = WebParam.Mode.IN, name = "bv_dName") String bv_dName,
                                          @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                          FindControl findControl) throws ServiceException;

    @WebMethod(action = "/oracle/summit/model/sdo/service/common/processEmpView1", operationName = "processEmpView1")
    @RequestWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/", localName = "processEmpView1")
    @ResponseWrapper(targetNamespace = "/oracle/summit/model/sdo/service/common/types/",
                     localName = "processEmpView1Response")
    @WebResult(name = "result")
    List<EmpViewSDO> processEmpView1(@WebParam(mode = WebParam.Mode.IN, name = "changeOperation")
                                     String changeOperation,
                                     @WebParam(mode = WebParam.Mode.IN, name = "empView1") List<EmpViewSDO> empView1,
                                     @WebParam(mode = WebParam.Mode.IN, name = "processControl")
                                     ProcessControl processControl) throws ServiceException;
}

