package oracle.summit.model.extend;

import oracle.summit.model.extend.common.ProductViewEx;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 16 15:40:07 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductViewExImpl extends ProductViewImpl implements ProductViewEx {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductViewExImpl() {
    }
    
    /**Gets the bind variable value for bv_ProductName.
     */
    public String getbv_ProductName() {
        return (String)getNamedWhereClauseParam("bv_ProductName");
    }

    /**Sets <code>value</code> for bind variable bv_ProductName.
     */
    public void setbv_ProductName(String value) {
        setNamedWhereClauseParam("bv_ProductName", value);
    }

}
