package oracle.summit.model.extend;

import oracle.summit.base.SummitViewObjectImpl;
import oracle.summit.model.extend.common.ProductView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 16 15:32:51 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductViewImpl extends SummitViewObjectImpl implements ProductView {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductViewImpl() {
    }
    
    public void someCustomMethodOnProducts(String arg) {
      System.out.println(">>>>>> someCustomMethodOnProducts Called");
    }
}
