package oracle.summit.model.extend;

import oracle.jbo.server.AttributeDefImpl;

import oracle.jbo.server.ViewDefImpl;

import oracle.summit.model.extend.common.ProductViewExRow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 16 15:41:41 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductViewExRowImpl extends ProductViewRowImpl implements ProductViewExRow {


    public static final int MAXUSAGECONST = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        SomeExtraAttr {
            public Object get(ProductViewExRowImpl obj) {
                return obj.getSomeExtraAttr();
            }

            public void put(ProductViewExRowImpl obj, Object value) {
                obj.setSomeExtraAttr((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = ViewDefImpl.getMaxAttrConst("oracle.summit.model.extend.ProductView");

        public abstract Object get(ProductViewExRowImpl object);

        public abstract void put(ProductViewExRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int SOMEEXTRAATTR = AttributesEnum.SomeExtraAttr.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProductViewExRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute SomeExtraAttr.
     * @return the SomeExtraAttr
     */
    public String getSomeExtraAttr() {
        return (String) getAttributeInternal(SOMEEXTRAATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SomeExtraAttr.
     * @param value value to set the  SomeExtraAttr
     */
    public void setSomeExtraAttr(String value) {
        setAttributeInternal(SOMEEXTRAATTR, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    public void someExtraFeature(String x) {
      System.out.println("## Called someExtraFeature of ProductViewExRowImpl");
    }
}
