package oracle.summit.model.extend.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 16 15:33:47 CDT 2012
// ---------------------------------------------------------------------
public interface ProductView extends ViewObject {
    void someCustomMethodOnProducts(String arg);
}
