package oracle.summit.model.extend.common;

import java.math.BigDecimal;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 21 08:36:07 CDT 2012
// ---------------------------------------------------------------------
public interface ProductViewRow extends Row {


    Integer getId();

    Integer getImageId();

    Integer getLongtextId();

    String getName();

    String getShortDesc();

    String getSomeValue();

    BigDecimal getSuggestedWhlslPrice();

    String getWhlslUnits();

    void setId(Integer value);

    void setImageId(Integer value);

    void setLongtextId(Integer value);

    void setName(String value);

    void setShortDesc(String value);

    void setSomeValue(String value);

    void setSuggestedWhlslPrice(BigDecimal value);

    void setWhlslUnits(String value);
}
