package oracle.summit.model.extend.common;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 16 15:48:19 CDT 2012
// ---------------------------------------------------------------------
public interface ProductViewEx extends ProductView {
    String getbv_ProductName();

    void setbv_ProductName(String value);
}
