package oracle.summitdi.model.queries.readonly;

import oracle.jbo.server.ViewObjectImpl;

import oracle.summitdi.model.queries.readonly.common.CustomersSearchView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 20 14:44:41 EST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomersSearchViewImpl extends ViewObjectImpl implements CustomersSearchView {
    /**
     * This is the default constructor (do not remove).
     */
    public CustomersSearchViewImpl() {
    }

    public void executeCountriesQuery(String searchTerm) {
        if (searchTerm != null && searchTerm.length() > 0) {
            removeApplyViewCriteriaName("CustomersByCountry");
            setcountry_var(searchTerm);
            setApplyViewCriteriaName("CustomersByCountry");
            executeQuery();
        } else {
            resetQueryValues();
        }
    }

    public void resetQueryValues() {
        removeApplyViewCriteriaName("CustomersByCountry");
        executeQuery();
    }

    /**
     * Returns the variable value for country_var.
     * @return variable value for country_var
     */
    public String getcountry_var() {
        return (String) ensureVariableManager().getVariableValue("country_var");
    }

    /**
     * Sets <code>value</code> for variable country_var.
     * @param value value to bind as country_var
     */
    public void setcountry_var(String value) {
        ensureVariableManager().setVariableValue("country_var", value);
    }
}

