package oracle.summit.model.amservice;

import java.util.List;

import oracle.jbo.server.ViewLinkImpl;

import oracle.jbo.server.ViewRowImpl;

import oracle.summit.base.SummitApplicationModuleImpl;
import oracle.summit.base.SummitViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 11 16:57:53 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ServiceAppModuleImpl extends SummitApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ServiceAppModuleImpl() {
    }

    /**
     * Container's getter for CustomersView.
     * @return CustomersView
     */
    public SummitViewObjectImpl getCustomersView() {
        return (SummitViewObjectImpl) findViewObject("CustomersView");
    }

    /**
     * Container's getter for OrdersView.
     * @return OrdersView
     */
    public SummitViewObjectImpl getOrdersView() {
        return (SummitViewObjectImpl) findViewObject("OrdersView");
    }

    /**
     * Container's getter for CustOrdersView.
     * @return CustOrdersView
     */
    public SummitViewObjectImpl getCustOrdersView() {
        return (SummitViewObjectImpl) findViewObject("CustOrdersView");
    }

    /**
     * Container's getter for SOrdCustomerIdFkLink1.
     * @return SOrdCustomerIdFkLink1
     */
    public ViewLinkImpl getSOrdCustomerIdFkLink1() {
        return (ViewLinkImpl) findViewLink("SOrdCustomerIdFkLink1");
    }
}
